spring.application.name=hms-frontend
server.port=8083
backend.base.url=http://localhost:8082/api
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.resources.static-locations=classpath:/static/
